### ISSUE TITLE
Update to use rnp master 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-rnp#1]
@ni4 could you help update the Formula to use riboseinc/rnp master? Thanks!

**Comment by ni4** [comment]
@ronaldtse Ok, sure!

**Comment by ni4** [comment]
@ronaldtse  done in c48c88f. Since we do not have release tarball yet it work only via the --HEAD installation, please see the updated readme.
Also currently you'll need to install botan with --HEAD option due to s2k.

**Comment by ronaldtse** [comment]
Thank you @ni4 ! Tried and it works. Perhaps we should remove "openssl" since it's not used in rnp anymore.

**Comment by ni4** [comment]
Np, I'll update formulae later today.

**Comment by ni4** [comment]
@ronaldtse Done. I guess I was correct by removing line regarding the geocouch :) ?

**Comment by ronaldtse** [comment]
You're absolutely right. Thank you 👍
