### ISSUE TITLE
Update RNP to latest version in formula

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-rnp#4]
@dewyatt could you help update this to the latest version of RNP? Thanks!

**Comment by ronaldtse** [comment]
Now we have releases so we no longer need to lock to HEAD.

**Comment by dewyatt** [comment]
I'll be sure to get this done in the next couple of days here.

**Comment by dewyatt** [comment]
Done in https://github.com/riboseinc/homebrew-rnp/pull/5
